name: Node Lib

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint - ${{ matrix.os }} -- Node v${{ matrix.node-version }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: Use latest NPM
        run: sudo npm i -g npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Security audit
        run: npm run security

  test:
    name: Test - ${{ matrix.os }} - Node v${{ matrix.node-version }} Webpack ${{ matrix.webpack-version }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [10.x, 12.x, 14.x]
        webpack-version: [latest, next]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Git for window OS
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf input

      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use latest NPM on ubuntu/macos
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: sudo npm i -g npm

      - name: Use latest NPM on windows
        if: matrix.os == 'windows-latest'
        run: npm i -g npm

      - name: Install webpack ${{ matrix.webpack-version }}
        run: npm i webpack@${{ matrix.webpack-version }}

      - name: Run tests for webpack version ${{ matrix.webpack-version }}
        run: npm test -- --ci

  publish-npm:
    if: github.event_name != 'pull_request'

    needs: test

    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Use latest NPM
        run: npm i -g npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-presents

      - name: Publish
        run: npx semantic-release
